### ISSUE TITLE
Support for Azure Function Keys?

### ISSUE THREAD

**Issue by ardalis** [lgulliver/blazor-webassembly-serverless-chat-demo#1]
I'm looking to implement something like this in a "real world" app and it would need to be secured. For Azure Functions it seems the simplest approach is require a Function Key or App Key. Where do I add that support in this sample?

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=csharp#obtaining-keys

I'm assuming it would go here:
https://github.com/lgulliver/blazor-webassembly-serverless-chat-demo/blob/master/ServerlessChat.Client/Pages/Index.razor#L41
and here:
https://github.com/lgulliver/blazor-webassembly-serverless-chat-demo/blob/master/ServerlessChat.Client/Pages/Index.razor#L63

but I'm not sure how to format it as a querystring (?code=) vs. using a header. Have you gotten this to work?

**Comment by lgulliver** [comment]
As the keys would have to be stored with the Blazor client, a good way to do it would be to add in a functions proxy instead. This means its essentially a very basic API gateway and you don't have to ship your secrets with the Blazor client and accidentally expose your keys.

Here's a rough example I did over on my Azureish Live show: https://github.com/AzureishLive/gitwatcher/tree/main/proxy

With this, it means that you can store your function keys in the proxy configuration instead and in the client, you make calls to the functions proxy instead. You can also use `appsettings.json` in the `wwwroot` folder instead of hard coding the URL like I did here to provide the URL to your functions proxy or function.

The repo at https://github.com/AzureishLive/gitwatcher/ will provide you with a closer real world example of using function proxies. It also uses SignalR as well.

Hope this helps!
